export interface IVelov {
    type: string,
    properties: {
        number: number,
        name: string,
        address: string,
        address2: string,
        commune: string,
        nmarrond: number,
        bonus: string,
        pole: string,
        lat: number,
        lng: number,
        bike_stands: number,
        status: string,
        available_bike_stands: number,
        available_bikes: number,
        availabilitycode: number,
        availability: string,
        banking: number,
        gid: number,
        last_update: string,
        last_update_fme: string,
        code_insee: string,
        langue: string,
        etat: string,
        nature: string,
        titre: string,
        description: string,
    },
    geometry: {
        type: string,
        coordinates: Array<number>
    }
}
