db.velov.drop();

db.velov.insertMany([
        {"type": "Feature",
            "properties": {
                "number": 4012,
                "name": "Place Adrien Godien",
                "address": "Place Adrien Godien",
                "address2": "angle Montée de la Boucle",
                "commune": "Lyon 4 ème",
                "nmarrond": 12,
                "bonus": "Non",
                "pole": "maillage",
                "lat": 45.779198505292328,
                "lng": 4.8409716233552409,
                "bike_stands": 19,
                "status": "OPEN",
                "available_bike_stands": 12,
                "available_bikes": 6,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 1103,
                "last_update": "2019\/03\/31 18:30:22",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69384",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.840971623355241, 45.779198505292328]}
        },
        {"type": "Feature",
            "properties": {
                "number": 8025,
                "name": "Dumont \/ Jouvet",
                "address": "rue santos-dumont",
                "address2": "",
                "commune": "Lyon 8 ème",
                "nmarrond": 25,
                "bonus": "Non",
                "pole": "maillage",
                "lat": 45.744460628994261,
                "lng": 4.8609937736791071,
                "bike_stands": 17,
                "status": "OPEN",
                "available_bike_stands": 10,
                "available_bikes": 7,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 897,
                "last_update": "2019\/03\/31 18:30:04",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69388",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.860993773679107, 45.744460628994261]}
        },
        {"type": "Feature",
            "properties": {
                "number": 1031,
                "name": "Place de la Paix",
                "address": "Place de la Paix",
                "address2": "En face de la poste",
                "commune": "Lyon 1 er",
                "nmarrond": 31,
                "bonus": "Non",
                "pole": "Opéra, métro A, mairie centrale",
                "lat": 45.768023612654652,
                "lng": 4.831741251718416,
                "bike_stands": 20,
                "status": "OPEN",
                "available_bike_stands": 11,
                "available_bikes": 7,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 1067,
                "last_update": "2019\/03\/31 18:27:48",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69381",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.831741251718416, 45.768023612654652]}
        },
        {"type": "Feature",
            "properties": {
                "number": 3037,
                "name": "Paul Bert \/ Garibaldi",
                "address": "209, Rue Paul Bert",
                "address2": "Face place des Martyrs de la Résistance",
                "commune": "Lyon 3 ème",
                "nmarrond": 37,
                "bonus": "Non",
                "pole": "maillage (piscine Garibaldi)",
                "lat": 45.757102858168174,
                "lng": 4.85348079711666,
                "bike_stands": 20,
                "status": "OPEN",
                "available_bike_stands": 12,
                "available_bikes": 8,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 859,
                "last_update": "2019\/03\/31 18:24:35",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69383",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.85348079711666, 45.757102858168174]}
        },
        {"type": "Feature",
            "properties": {
                "number": 5045,
                "name": "Valdo \/ Rivet",
                "address": "Rue Jeunet",
                "address2": "",
                "commune": "Lyon 5 ème",
                "nmarrond": 45,
                "bonus": "Oui",
                "pole": "Maillage",
                "lat": 45.750481483431024,
                "lng": 4.7887741211031214,
                "bike_stands": 18,
                "status": "OPEN",
                "available_bike_stands": 18,
                "available_bikes": 0,
                "availabilitycode": 3,
                "availability": "Orange",
                "banking": 0,
                "gid": 883,
                "last_update": "2019\/03\/31 18:27:18",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69385",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.788774121103121, 45.750481483431024]}
        },
        {"type": "Feature",
            "properties": {
                "number": 7009,
                "name": "Jean Jaurès",
                "address": "avenue Jean Jaurès",
                "address2": "Angle rue Fourcade",
                "commune": "Lyon 7 ème",
                "nmarrond": 9,
                "bonus": "Non",
                "pole": "métro B",
                "lat": 45.737794826260711,
                "lng": 4.8375855217711159,
                "bike_stands": 16,
                "status": "OPEN",
                "available_bike_stands": 13,
                "available_bikes": 3,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 1081,
                "last_update": "2019\/03\/31 18:29:48",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69387",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.837585521771116, 45.737794826260711]}
        },
        {"type": "Feature",
            "properties": {
                "number": 3101,
                "name": "Patinoire Baraban",
                "address": "Face 34 rue Baraban",
                "address2": "",
                "commune": "Lyon 3 ème",
                "nmarrond": 101,
                "bonus": "Non",
                "pole": "Patinoire, activités",
                "lat": 45.762585664618541,
                "lng": 4.8686111248701751,
                "bike_stands": 20,
                "status": "OPEN",
                "available_bike_stands": 6,
                "available_bikes": 14,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 781,
                "last_update": "2019\/03\/31 18:26:20",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69383",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.868611124870175, 45.762585664618541]}
        },
        {"type": "Feature",
            "properties": {
                "number": 6031,
                "name": "Lafayette \/ Corneille",
                "address": "64, Rue Pierre Corneille",
                "address2": "angle Cours Lafayette",
                "commune": "Lyon 6 ème",
                "nmarrond": 31,
                "bonus": "Non",
                "pole": "maillage",
                "lat": 45.763759478341875,
                "lng": 4.8437773405191873,
                "bike_stands": 13,
                "status": "OPEN",
                "available_bike_stands": 6,
                "available_bikes": 6,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 943,
                "last_update": "2019\/03\/31 18:29:40",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69386",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.843777340519187, 45.763759478341875]}
        },
        {
            "type": "Feature", "properties": {
                "number": 3001,
                "name": "Part-Dieu \/ Vivier Merle",
                "address": "Place Béraudier",
                "address2": "derrière la station tram",
                "commune": "Lyon 3 ème",
                "nmarrond": 1,
                "bonus": "Non",
                "pole": "gare",
                "lat": 45.760263005893833,
                "lng": 4.8584641754302078,
                "bike_stands": 40,
                "status": "OPEN",
                "available_bike_stands": 0,
                "available_bikes": 0,
                "availabilitycode": 0,
                "availability": "Gris",
                "banking": 0,
                "gid": 845,
                "last_update": "2019\/03\/31 00:30:00",
                "last_update_fme": "2019\/03\/31 00:30:00",
                "code_insee": "69383",
                "langue": "FR",
                "etat": "CLOSING",
                "nature": "WORKS",
                "titre": "Fermeture stations Place Béraudier",
                "description": "La gare de la Part-Dieu poursuit sa transformation afin de mieux vous accueillir. \nEn raison des travaux du parvis qui vont débuter prochainement, les stations n°3001\/Part-Dieu – Vivier Merle et n°3002\/Part-Dieu – Gare SNCF fermeront le 20 février. \nRetrouvez-nous à la station Vélo’v n°3011\/Part-Dieu – Cuirassiers juste de l’autre côté du boulevard Vivier Merle.\nTéléchargez l’application « Vélo’v officiel » pour accéder au service et connaitre en temps réel les places et Vélo’v disponibles.\nPensez à ajouter vos stations préférées à vos favoris afin de recevoir toutes les informations les concernant.\n",
                "startdate": "2019\/02\/20 00:00:00",
                "enddate": "2021\/02\/19 00:00:00"
            }, "geometry": {"type": "Point", "coordinates": [4.858464175430208, 45.760263005893833]}
        },
        {"type": "Feature",
            "properties": {
                "number": 3009,
                "name": "Musée Africain",
                "address": "133, 137 Cours Gambetta",
                "address2": "",
                "commune": "Lyon 3 ème",
                "nmarrond": 9,
                "bonus": "Non",
                "pole": "Université Jean Moulin, musée africain, commerces",
                "lat": 45.750253311906036,
                "lng": 4.8579250300630621,
                "bike_stands": 22,
                "status": "OPEN",
                "available_bike_stands": 15,
                "available_bikes": 7,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 1026,
                "last_update": "2019\/03\/31 18:26:17",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69383",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.857925030063062, 45.750253311906036]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10091,
                "name": "Château Gaillard \/ Fort",
                "address": "rue louis fort",
                "address2": "",
                "commune": "VILLEURBANNE",
                "nmarrond": 91,
                "bonus": "Non",
                "pole": "maillage",
                "lat": 45.774750799311725,
                "lng": 4.8880387408797779,
                "bike_stands": 16,
                "status": "OPEN",
                "available_bike_stands": 2,
                "available_bikes": 14,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 981,
                "last_update": "2019\/03\/31 18:26:16",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.888038740879778, 45.774750799311725]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10111,
                "name": "Charles Hernu",
                "address": "95, Cours Vitton",
                "address2": "",
                "commune": "VILLEURBANNE",
                "nmarrond": 111,
                "bonus": "Non",
                "pole": "Métro, Tram",
                "lat": 45.770333043820656,
                "lng": 4.8622578196582271,
                "bike_stands": 16,
                "status": "OPEN",
                "available_bike_stands": 13,
                "available_bikes": 3,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 965,
                "last_update": "2019\/03\/31 18:29:05",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.862257819658227, 45.770333043820656]}
        },
        {"type": "Feature",
            "properties": {
                "number": 7008,
                "name": "Jean Jaurès \/ Guillotière",
                "address": "avenue Jean Jaurès",
                "address2": "angle rue de la Guillotière",
                "commune": "Lyon 7 ème",
                "nmarrond": 8,
                "bonus": "Non",
                "pole": "maillage",
                "lat": 45.752573064361876,
                "lng": 4.8463632200533286,
                "bike_stands": 10,
                "status": "OPEN",
                "available_bike_stands": 8,
                "available_bikes": 1,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 963,
                "last_update": "2019\/03\/31 18:29:08",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69387",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.846363220053329, 45.752573064361876]}
        },
        {"type": "Feature",
            "properties": {
                "number": 7030,
                "name": "Quartier Général Frère",
                "address": "31 boulevard Yves Farge",
                "address2": "",
                "commune": "Lyon 7 ème",
                "nmarrond": 30,
                "bonus": "Non",
                "pole": "Parc d'activités, logement, projet cyclable",
                "lat": 45.74322179772394,
                "lng": 4.8342510240081396,
                "bike_stands": 30,
                "status": "OPEN",
                "available_bike_stands": 11,
                "available_bikes": 19,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 990,
                "last_update": "2019\/03\/31 18:23:55",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69387",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.83425102400814, 45.74322179772394]}
        },
        {"type": "Feature",
            "properties": {
                "number": 11003,
                "name": "La Rochette",
                "address": "Place de la Rochette",
                "address2": "",
                "commune": "CALUIRE-ET-CUIRE",
                "nmarrond": 3,
                "bonus": "Non",
                "pole": "",
                "lat": 45.791670182603994,
                "lng": 4.8235970239637442,
                "bike_stands": 20,
                "status": "OPEN",
                "available_bike_stands": 12,
                "available_bikes": 8,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 956,
                "last_update": "2019\/03\/31 18:28:29",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69034",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.823597023963744, 45.791670182603994]}
        },
        {"type": "Feature",
            "properties": {
                "number": 1001,
                "name": "Terreaux \/ Terme",
                "address": "Rue Terme",
                "address2": "Angle rue d'Algérie",
                "commune": "Lyon 1 er",
                "nmarrond": 1,
                "bonus": "Non",
                "pole": "",
                "lat": 45.767734686369856,
                "lng": 4.8321350621908303,
                "bike_stands": 16,
                "status": "OPEN",
                "available_bike_stands": 12,
                "available_bikes": 4,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 811,
                "last_update": "2019\/03\/31 18:28:57",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69381",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.83213506219083, 45.767734686369856]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10103,
                "name": "DOUA \/ Rue des sports",
                "address": "Rue des Arts",
                "address2": "",
                "commune": "VILLEURBANNE",
                "nmarrond": 103,
                "bonus": "Non",
                "pole": "Tennis, stade, piscine",
                "lat": 45.784485187238431,
                "lng": 4.8774042325766302,
                "bike_stands": 30,
                "status": "OPEN",
                "available_bike_stands": 19,
                "available_bikes": 11,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 968,
                "last_update": "2019\/03\/31 18:25:50",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.87740423257663, 45.784485187238431]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10080,
                "name": "Vaillant\/Perroncel",
                "address": "Rue Alexis Perroncel",
                "address2": "",
                "commune": "VILLEURBANNE",
                "nmarrond": 80,
                "bonus": "Non",
                "pole": "Maillage, itinéraire cyclable",
                "lat": 45.775425991547074,
                "lng": 4.8802898713340195,
                "bike_stands": 17,
                "status": "OPEN",
                "available_bike_stands": 14,
                "available_bikes": 2,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 971,
                "last_update": "2019\/03\/31 18:30:48",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.880289871334019, 45.775425991547074]}
        },
        {"type": "Feature",
            "properties": {
                "number": 3089,
                "name": "Trarieux \/ Lacassagne",
                "address": "221 avenue Lacassagne",
                "address2": "",
                "commune": "Lyon 3 ème",
                "nmarrond": 89,
                "bonus": "Non",
                "pole": "Ecole d'infirmière",
                "lat": 45.745314592733372,
                "lng": 4.8889645723972111,
                "bike_stands": 24,
                "status": "OPEN",
                "available_bike_stands": 20,
                "available_bikes": 4,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 918,
                "last_update": "2019\/03\/31 18:27:54",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69383",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.888964572397211, 45.745314592733372]}
        },
        {"type": "Feature",
            "properties": {
                "number": 5055,
                "name": "Buyer \/ Apollinaire",
                "address": "111 av. Barthélémy Buyer",
                "address2": "",
                "commune": "Lyon 5 ème",
                "nmarrond": 55,
                "bonus": "Oui",
                "pole": "Centre commercial",
                "lat": 45.761798619484843,
                "lng": 4.8030613972282632,
                "bike_stands": 22,
                "status": "OPEN",
                "available_bike_stands": 22,
                "available_bikes": 0,
                "availabilitycode": 3,
                "availability": "Orange",
                "banking": 0,
                "gid": 891,
                "last_update": "2019\/03\/31 18:30:15",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69385",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.803061397228263, 45.761798619484843]}
        },
        {"type": "Feature",
            "properties": {
                "number": 7011,
                "name": "Berthelot \/ Garibaldi",
                "address": "rue Garibaldi",
                "address2": "angle avenue Berthelot",
                "commune": "Lyon 7 ème",
                "nmarrond": 11,
                "bonus": "Non",
                "pole": "tram, itinéraires cyclables",
                "lat": 45.743719525342676,
                "lng": 4.847275267998711,
                "bike_stands": 10,
                "status": "OPEN",
                "available_bike_stands": 7,
                "available_bikes": 3,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 1083,
                "last_update": "2019\/03\/31 18:28:03",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69387",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.847275267998711, 45.743719525342676]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10117,
                "name": "La Pérralière",
                "address": "171 rue Léon Blum",
                "address2": "",
                "commune": "VILLEURBANNE",
                "nmarrond": 117,
                "bonus": "Non",
                "pole": "Centre de quartier, commerces",
                "lat": 45.764563666529412,
                "lng": 4.8923336071821142,
                "bike_stands": 22,
                "status": "OPEN",
                "available_bike_stands": 3,
                "available_bikes": 18,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 922,
                "last_update": "2019\/03\/31 18:25:28",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.892333607182114, 45.764563666529412]}
        },
        {"type": "Feature",
            "properties": {
                "number": 9041,
                "name": "Carret \/ Sédaillan",
                "address": "30 quai Paul Sédaillan",
                "address2": "",
                "commune": "Lyon 9 ème",
                "nmarrond": 41,
                "bonus": "Non",
                "pole": "Activités, logement, maillage",
                "lat": 45.792567265345831,
                "lng": 4.8206351679845865,
                "bike_stands": 18,
                "status": "OPEN",
                "available_bike_stands": 0,
                "available_bikes": 18,
                "availabilitycode": 2,
                "availability": "Bleu",
                "banking": 0,
                "gid": 929,
                "last_update": "2019\/03\/31 18:28:40",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69389",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.820635167984586, 45.792567265345831]}
        },
        {"type": "Feature",
            "properties": {
                "number": 5004,
                "name": "Saint Jean",
                "address": "Rue Saint-Jean",
                "address2": "entre entrée de la Cathédrale et le métro",
                "commune": "Lyon 5 ème",
                "nmarrond": 4,
                "bonus": "Non",
                "pole": "funiculaire, coeur quartier, Vieux Lyon",
                "lat": 45.76048374389778,
                "lng": 4.8265650503972601,
                "bike_stands": 29,
                "status": "OPEN",
                "available_bike_stands": 19,
                "available_bikes": 19,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 854,
                "last_update": "2019\/03\/31 18:30:03",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69385",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.82656505039726, 45.76048374389778]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10118,
                "name": "Voyant \/ Chambord",
                "address": "92 rue Voyant",
                "address2": "",
                "commune": "VILLEURBANNE",
                "nmarrond": 118,
                "bonus": "Non",
                "pole": "Commerces, centre social",
                "lat": 45.767153312728034,
                "lng": 4.9005991607433979,
                "bike_stands": 22,
                "status": "OPEN",
                "available_bike_stands": 19,
                "available_bikes": 2,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 962,
                "last_update": "2019\/03\/31 18:21:45",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.900599160743398, 45.767153312728034]}
        },
        {"type": "Feature",
            "properties": {
                "number": 3008,
                "name": "Institut Lumière",
                "address": "Cours Albert Thomas",
                "address2": "",
                "commune": "Lyon 3 ème",
                "nmarrond": 8,
                "bonus": "Non",
                "pole": "Métro, coeur quartier, institut Lumière, marché",
                "lat": 45.745809569291112,
                "lng": 4.8706875747775999,
                "bike_stands": 18,
                "status": "OPEN",
                "available_bike_stands": 16,
                "available_bikes": 2,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 793,
                "last_update": "2019\/03\/31 18:28:57",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69383",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.8706875747776, 45.745809569291112]}
        },
        {"type": "Feature",
            "properties": {
                "number": 3071,
                "name": "BioParc",
                "address": "60 avenue Rockefeller",
                "address2": "",
                "commune": "Lyon 3 ème",
                "nmarrond": 71,
                "bonus": "Non",
                "pole": "Pôle d'habitation, Bio Parc, Faculté de Médecine",
                "lat": 45.740483091025865,
                "lng": 4.8880858101360474,
                "bike_stands": 20,
                "status": "OPEN",
                "available_bike_stands": 19,
                "available_bikes": 0,
                "availabilitycode": 3,
                "availability": "Orange",
                "banking": 0,
                "gid": 997,
                "last_update": "2019\/03\/31 18:28:00",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69383",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.888085810136047, 45.740483091025865]}
        },
        {"type": "Feature",
            "properties": {
                "number": 5006,
                "name": "Quai Romain Rolland",
                "address": "Quai Romain Rolland",
                "address2": "Face au Palais de Justice",
                "commune": "Lyon 5 ème",
                "nmarrond": 6,
                "bonus": "Non",
                "pole": "Vieux Lyon",
                "lat": 45.762037080692672,
                "lng": 4.8288896824580405,
                "bike_stands": 17,
                "status": "OPEN",
                "available_bike_stands": 2,
                "available_bikes": 15,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 1030,
                "last_update": "2019\/03\/31 18:29:56",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69385",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.828889682458041, 45.762037080692672]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10014,
                "name": "Gare Laurent Bonnevay",
                "address": "Rue du Sytral",
                "address2": "",
                "commune": "VILLEURBANNE",
                "nmarrond": 14,
                "bonus": "Non",
                "pole": "Gare, métro",
                "lat": 45.765124055355358,
                "lng": 4.9098182197044347,
                "bike_stands": 29,
                "status": "OPEN",
                "available_bike_stands": 24,
                "available_bikes": 4,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 980,
                "last_update": "2019\/03\/31 18:21:34",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.909818219704435, 45.765124055355358]}
        },
        {"type": "Feature",
            "properties": {
                "number": 10004,
                "name": "Tonkin",
                "address": "Rue Salvador Allende",
                "address2": "Angle avenue du Lys Orangé, au pied de la",
                "commune": "VILLEURBANNE",
                "nmarrond": 4,
                "bonus": "Non",
                "pole": "centre quartier, itinéraire cyclable",
                "lat": 45.776221014708135,
                "lng": 4.8626475813297994,
                "bike_stands": 10,
                "status": "OPEN",
                "available_bike_stands": 7,
                "available_bikes": 3,
                "availabilitycode": 1,
                "availability": "Vert",
                "banking": 0,
                "gid": 1021,
                "last_update": "2019\/03\/31 18:23:56",
                "last_update_fme": "2019\/03\/31 18:31:16",
                "code_insee": "69266",
                "langue": "",
                "etat": "",
                "nature": "",
                "titre": "",
                "description": ""
            },
            "geometry": {"type": "Point", "coordinates": [4.862647581329799, 45.776221014708135]}
        }
    ]
);
